dataset:
  data_encoding: "ISO-8859-1"
  train_size: 0.8
  test_size: 0.2

text_vectoriser:
  max_features: 300000
  ngram_range: [1, 2]

model_params:
  C: 2.0
  max_iter: 1000
  n_jobs: -1
  penalty: 'l2'
  solver: 'saga'
  class_weight: 'balanced'