artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_dir: raw.zip
  unzip_dir: artifacts/data_ingestion
  dataset_file: artifacts/data_ingestion/raw.csv
  train_data_dir: artifacts/data_ingestion/train
  test_data_dir: artifacts/data_ingestion/test

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  file_check_dir: artifacts/data_ingestion
  FILE_NAMES: ["test", "train"]